name: test submodule
on:
 push:
  branches: 'main'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          # token: ${{ secrets.GITHUB_TOKEN }}
          
  
